{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.workflowRunner.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-workflow-runner
  labels:
    app: workflow-runner
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: workflow-runner
{{- end }}
